// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTphHg5nccu2stesadJ-QQm5gkjJfnhk',
    appId: '1:236128171180:web:dfb834321b909cbb205b09',
    messagingSenderId: '236128171180',
    projectId: 'eger-map-app',
    authDomain: 'eger-map-app.firebaseapp.com',
    storageBucket: 'eger-map-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GCEyNLTpcoovwlIGxG93_iwSy89wR2I',
    appId: '1:236128171180:android:10ecf4ff20fa6a24205b09',
    messagingSenderId: '236128171180',
    projectId: 'eger-map-app',
    storageBucket: 'eger-map-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxfmp2fM_3IMTlae_I7nTRhWXg_CX_cJ8',
    appId: '1:236128171180:ios:ee9affd9aa08e142205b09',
    messagingSenderId: '236128171180',
    projectId: 'eger-map-app',
    storageBucket: 'eger-map-app.firebasestorage.app',
    androidClientId: '236128171180-uo9mtag2gd022df1mgpihb9al04ilnln.apps.googleusercontent.com',
    iosClientId: '236128171180-jrsof50acto8ljshb1hctoetckn9k1ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxfmp2fM_3IMTlae_I7nTRhWXg_CX_cJ8',
    appId: '1:236128171180:ios:ee9affd9aa08e142205b09',
    messagingSenderId: '236128171180',
    projectId: 'eger-map-app',
    storageBucket: 'eger-map-app.firebasestorage.app',
    androidClientId: '236128171180-uo9mtag2gd022df1mgpihb9al04ilnln.apps.googleusercontent.com',
    iosClientId: '236128171180-jrsof50acto8ljshb1hctoetckn9k1ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWTphHg5nccu2stesadJ-QQm5gkjJfnhk',
    appId: '1:236128171180:web:4a7199fb9fee0557205b09',
    messagingSenderId: '236128171180',
    projectId: 'eger-map-app',
    authDomain: 'eger-map-app.firebaseapp.com',
    storageBucket: 'eger-map-app.firebasestorage.app',
  );

}